version: "3"

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

env_file:
      - .env # configure postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data